# change name here
name: build and push nodejs images

on:
  schedule:
    - cron: "0 3 * * 0"
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      # path to listen
      - nodejs/*/Dockerfile
      - nodejs/entrypoint.sh

jobs:
  docker:
    name: Build and Push to Docker Hub ${{ github.repository_owner }}/pterodactyl:nodejs_${{ matrix.tag }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ['12', '14', '15', '16']
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2
      # https://github.com/docker/setup-qemu-action
      - uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      # https://github.com/docker/login-action
      - uses: docker/login-action@v1
        with:
          # https://hub.docker.com/settings/security
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # https://github.com/docker/build-push-action
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          # path to source
          context: nodejs/
          file: nodejs/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          # name:tag
          tags: ${{ github.repository_owner }}/pterodactyl:nodejs_${{ matrix.tag }}