# change name here
name: build nodejs_14 image

on:
  push:
    branches: [ main ]
    paths:
      # path to listen
      - nodejs/14/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        id: docker_login
        uses: docker/login-action@v1
        with:
          # https://hub.docker.com/settings/security
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # https://github.com/docker/build-push-action
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          # path to source
          context: nodejs/14/
          file: nodejs/14/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          # name:tag
          tags: ${{ secrets.DOCKER_USERNAME }}/pterodactyl:nodejs_14