# change name here
name: build and push software images

on:
  schedule:
    - cron: "0 3 * * 0"
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      # path to listen
      - software/omada/Dockerfile
      - software/omada/entrypoint.sh
      - software/omada/install.sh

jobs:
  docker:
    env:
      suffix: omada
    name: Build and Push to Docker Hub ${{ github.repository_owner }}/pterodactyl:omada_${{ matrix.tag }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ['base']
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2
      # https://github.com/docker/setup-qemu-action
      - uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      # https://github.com/docker/login-action
      - uses: docker/login-action@v1
        with:
          # https://hub.docker.com/settings/security
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set dynamic env values
        run: |
          echo created=$(date -u +'%Y-%m-%dT%H:%M:%SZ') >> $GITHUB_ENV
      # https://github.com/docker/build-push-action
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          #build-args: |
          #  VERSION=${{ matrix.tag }}
          context: software/${{ env.suffix }}/
          file: software/${{ env.suffix }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ github.repository_owner }}/pterodactyl:${{ env.suffix }}_${{ matrix.tag }}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ env.created }}
            org.opencontainers.image.source=${{ github.event.repository.html_url }}